### ISSUE TITLE
Layer with same sensitivity doesn't move the same distance

### ISSUE THREAD

**Issue by OshidaBCF** [jszczerbinsky/lwp#12]
Two of my layers have the same sensitivity value, but one move more than the other

It seem that each sensitivity "depend" of another at some point, because this is what the wallpaper is supposed to look like

mouse on the left edge
![image](https://user-images.githubusercontent.com/61458287/218306341-2e55a72a-a0b2-4352-afc5-e8de4a9e2731.png)
mouse on the right edge
![image](https://user-images.githubusercontent.com/61458287/218306348-bf611c39-771b-4782-ac9b-7bd83258700d.png)

And this is the result i get
https://cdn.discordapp.com/attachments/879979752658718760/1074277420020023316/2023-02-12_11-34-22.mp4
You can see the tips of this water spall is moving compared to the "matt" of the ship behind, Those two layers, 10 and 17 both have a sensitivity of -0.001, so they should move the same amount right ?

**Comment by jszczerbinsky** [comment]
It's because each layer has to move faster than the previous one. 
Setting global movementX results in all layers having the same per layer movement, yet each next of them has to move a little faster to make a feeling, that some layers are closer to You. 

So the sensitivity of each layer is `movement * i`, where `i` is number of the layer counting from 0.

So all of this is not a bug, it's a desired behavior, but I think I could add some way to force sensitivity  of the layer

**Comment by OshidaBCF** [comment]
Ohhhhhh, so i just need to divide each sensitivity by the layer number ?

That's very smart yet simple

**Comment by OshidaBCF** [comment]
Indeed, now it's working
