### ISSUE TITLE
Support for Wayland

### ISSUE THREAD

**Issue by jamielinux** [jszczerbinsky/lwp#29]
Cool project!

You [mentioned on HN](https://news.ycombinator.com/item?id=34915404) that it doesn't support Wayland yet, but you're planning to add that support at some point.

Just creating an issue to track it :)

**Comment by dginovker** [comment]
Works on Wayland for me

**Comment by jszczerbinsky** [comment]
I've made some changes and now it seams to works with XWayland. The interesting thing is that it should work

**Comment by jszczerbinsky** [comment]
I've made some changes and now it seams to work with XWayland. 

The problem was, that on wayland SDL couldn't use  X11 window, that has been created earlier, but there was no error. SDL was working perfectly fine, although it didn't draw on the window for some reason. Creating a window using SDL and then configuring it to work as a "wallpaper window" turned out to be a solution.

I think it's because of some bug related to using SDL on XWayland, which happens on some specific versions of them. And that would explain why it was working on @dginovker's setup and didn't work on mine. 

Also we can't be sure, that this is a final solution, so in case of any problems related to this one, please reopen this issue.
