### ISSUE TITLE
Windows 11 config file problem

### ISSUE THREAD

**Issue by DivineSilverWolf** [jszczerbinsky/lwp#63]
![image](https://github.com/jszczerbinsky/lwp/assets/73995020/ba175453-023b-4fc9-ba8e-c126cefeed14)
The essence of the problem is shown in the picture. I run the program through the standard settings of your configuration file and the parser of your program does not read the configuration file, freezing at a certain moment. For clarity, I ran it through bash, but it also freezes during normal launches. Installed your program through the Windows installer

**Comment by jszczerbinsky** [comment]
Layered WallPaper hasn't been tested on Windows 11, so this could be a bug. 
I suppose this is a user config file (the one in AppData ), because the program would print a message if it failed to load it. If that's the case, try deleting (or renaming) it and let the program use the default one instead. Let me know if it works.

**Comment by DivineSilverWolf** [comment]
Hello dear jszczerbinsky! The default file didn't work either, so after that I already tried to put my custom one, which also did not lead to anything. Thank you for giving me your time!

**Comment by jszczerbinsky** [comment]
This is almost certainly related to some bug of config parser. The latest version uses `libconfig` to parse configuration files, so I'm going to close this issue.
