### ISSUE TITLE
Desktop Icons Disappear on Fedora 39, X11

### ISSUE THREAD

**Issue by nasawyer7** [jszczerbinsky/lwp#67]
Had to use display manager x11 since wayland does not work (see other issue). But As title said, desktop icons disappear. I found a similar repo that enables live wallpapers, and to fix this they used this command. 
gsettings set org.gnome.desktop.background show-desktop-icons true || true
gsettings set org.nemo.desktop show-desktop-icons true || true

However, I am on x11 kde not using gnome. So, I tried to remake this command for this display manager by asking chatgpt since i know nothing about this section myself lol. Anyways, the command actually seemed to work surprisingly. here it is. 

kwriteconfig5 --file ~/.config/plasma-org.kde.plasma.desktop-appletsrc --group Containments --group 1 --group General --group ShortcutsContainment --group ActionPlugins --group 0 --group Shortcuts --group 49 --group Data --key enabled --type bool true || true
Anyways, help would be appreciated!

**Comment by jszczerbinsky** [comment]
Hi, after a long time of investigating this bug I finally found a solution.

![Screenshot_20240127_003448](https://github.com/jszczerbinsky/lwp/assets/38699473/dd1c832e-a519-4599-b0ea-0122a44af850)

The problem is that KDE renders desktop, widgets and icons on the same window, so it's impossible to render something in-between. The solution is quite ugly, but also tricky. I tested it on KDE plasma 5.27.10 and it works.

The solution:

1. You need to make the background color transparent. Unfortunately the color picker doesn't allow You to do this, but I checked and realized, that You can set alpha chanell manually in the config file. You can use this script:
2.

**Comment by jszczerbinsky** [comment]
Hi, after a long time of investigating this bug I finally found a solution.

![Screenshot_20240127_003448](https://github.com/jszczerbinsky/lwp/assets/38699473/f5a3e371-dd14-442b-ade5-db45075f486d)

The problem is that KDE renders desktop, widgets and icons on the same window, so it's impossible to render something in-between. The solution is quite ugly, but also tricky. I tested it on KDE plasma 5.27.10 and it works. The key idea is to put Layered WallPaper window behind the plasma desktop and make the desktop background transparent.

The solution:

First of all You need to make the background color transparent. Unfortunately the color picker doesn't allow You to do this, but I realized, that You can set the alpha channel manually in the config file. You can use this script:

```bash
kwriteconfig5 --file ~/.config/plasma-org.kde.plasma.desktop-appletsrc --group Containments --group 1 --group Wallpaper --group org.kde.color --group General --key Color 0,0,0,0
```

Next, open the compositor settings (System Settings -> Display and Monitor -> Compositor) and uncheck the `Allow applications to block compositing` checkbox.

![Screenshot_20240127_005516](https://github.com/jszczerbinsky/lwp/assets/38699473/b376a03a-c341-40f8-b09a-a4306841f169)

From now on the plasma desktop window can be managed by the compositor. 

The next step is setting the window rules for the compositor (System Settings -> Window Management -> Window Rules). You can unzip this file and import them: [window_rules.zip](https://github.com/jszczerbinsky/lwp/files/14070242/window_rules.zip) or just set them as in the screenshots:

![Screenshot_20240127_012257](https://github.com/jszczerbinsky/lwp/assets/38699473/b537c479-8e11-4d4e-9c21-de26223c9f20)

![Screenshot_20240127_010816](https://github.com/jszczerbinsky/lwp/assets/38699473/60c1477e-1a18-4324-9b8f-de5e092078f3)

I found it interesting, that even if the background is already set to transparent, the compositor doesn't allow the window to show transparency (it just renders black color), but You can set the rule for window opacity and force it to allow the alpha channel. This rule without setting the background is not a solution, because it makes the icons transparent too, that's why You need to set the transparent background anyway and that's why the rules for opacity are set to 99% - to allow the alpha channel while not making the icons too transparent.

Now everything will work smoothly only if Layered WallPaper is started before the desktop. To achieve it create a startup script:

```bash
touch ~/.config/plasma-workspace/env/runLwp.sh
chmod +x ~/.config/plasma-workspace/env/runLwp.sh
```

and put the following content inside of it:

```bash
exec lwp &
sleep 1
```

After rebooting you system everything should work fine
