### ISSUE TITLE
Can't uninstall it

### ISSUE THREAD

**Issue by MiniMinnoww** [jszczerbinsky/lwp#84]
Downloaded the version for windows, and for reasons (mainly because I have 2 monitors and it messes up the background) I want to uninstall the app. I don't want to just leave it on my computer as currently my computer just has a black background (I removed the folder with wallpaper in it).
Also the "Turn off layered wallpaper" setting doesn't save when you restart the computer, so that isn't an option either.

I've tried searching for the program, both in the windows search bar as well as my program files directory, but it always seems to regenerate.

So, how do I uninstall it?

**Comment by jszczerbinsky** [comment]
Turn off settings doesn't save, because it's not intended to do it. If you want to disable it from starting automatically, you can do it from the Task Manager under Startup tab.

What do You mean by "seems to regenerate"?

The only proper way to uninstall it is to do it from the Windows Control Panel.
