### ISSUE TITLE
Add possibility to use images "larger" than screen

### ISSUE THREAD

**Issue by OshidaBCF** [jszczerbinsky/lwp#9]
I'm making a wallpaper with images that are 2700x1080, but my screen is 1920x1080, so the layers get squeezed a bit and break all the parallax effect because the "edges" of each layer appears and get also repeated

This is what the wallpaper looks like
![image](https://user-images.githubusercontent.com/61458287/218279909-ef7444f6-54bb-49e9-9b67-7d0bb3884f79.png)

This is how it should look
![Scharnhorst_960](https://user-images.githubusercontent.com/61458287/218279472-8d6fce2e-f89c-4b87-bd25-91e4200855ae.png)

is this even doable with windows ?

**Comment by jszczerbinsky** [comment]
The problem here is that image ratio is different than 1920x1080 ratio (wallpaper is wider, but has the same height as Your screen) so there is no way to display whole wallpaper without sqeezing, cropping or letting the wallpaper to overflow the wallpaper. 

I suggest setting wallpaper's width to be the same as image. Then some part of the wallpaper (720px) will overflow on the right side of the screen and won't be displayed, but You will preserve original aspect ratio so it will  no longer be squeezed. 

You could also crop the layers in gimp/Photoshop from the left side if You prefer cropping the left side instead of right side. In this case each layer has to be cropped the same amount from each side to preserve correct layer position.

**Comment by OshidaBCF** [comment]
I managed to do just that, by putting the X at -390 and the width at 2700, the scale is correct, my second screen always have discord on it so even if it overflow there it's not a problem

I'm surprised neither the app nor windows crash when going -390
